name: Sync Files to Another Repo

on:
  push:
    branches:
      - main  # Change to your branch if needed
    paths:
      - "files_to_copy/**"  # Change to the files/folders you want to copy

jobs:
  sync-files:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout Source Repository
        uses: actions/checkout@v3

      - name: Clone Target Repository
        env:
          GH_PAT: ${{ secrets.GH_PAT }}
        run: |
          git clone https://$GH_PAT@github.com/mejiaeverardo/Professional-Development.git target-repo
          cp -r files_to_copy/* target-repo/  # Copy files
          cd target-repo
          git config --global user.name "github-actions[bot]"
          git config --global user.email "github-actions[bot]@users.noreply.github.com"
          git add .
          git commit -m "Sync files from source repository"
          git push origin main  # Change branch if needed
